### ISSUE TITLE
pod2html cannot be used in parallel

### ISSUE THREAD

**Issue by antoniogamiz** [Raku/Pod-To-HTML#63]
I'm trying to generate a lot of documents at the same time, but if I try to use pod2html, a core is dumped.

I have made a "little" script to reproduce it. You need to have installed [Pod::To::Cached](https://github.com/finanalyst/pod-cached) and a copy of the doc directory (no the repo) from https://github.com/perl6/doc.

Here is the [code](https://gist.github.com/antoniogamiz/3625d853398aa6e5f1820d46cff7050e) to reproduce it.

**Comment by JJ** [comment]
Can you please copy paste the error here too?

**Comment by antoniogamiz** [comment]
Error message:
~~~
Source verified
Got cache at .doc
Cache fully updated
starting worker 0
starting worker 1
starting worker 2
starting worker 3
starting worker 4
starting worker 5
starting worker 6
starting worker 7
[1]    7578 segmentation fault (core dumped)  perl6 test.p6
~~~

**Comment by JJ** [comment]
Thanks!

**Comment by Altai-man** [comment]
Closing as the PR drastically improving the situation was merged, please re-open otherwise.
