### ISSUE TITLE
=TITLE and =SUBTITLE seems to be ignored

### ISSUE THREAD

**Issue by antoniogamiz** [Raku/Pod-To-HTML#70]
Hi, using the new version of Pod::To::HTML I have found that `=TITLE` and `=SUBTITLE` seems to be ignored:

![image](https://user-images.githubusercontent.com/22995015/86124159-f25c6600-bada-11ea-8866-0c0a62fa5d6e.png)

The output should be something like this:

![image](https://user-images.githubusercontent.com/22995015/86124269-259ef500-badb-11ea-9830-d6ab6939ff38.png)

**Comment by antoniogamiz** [comment]
Yep, that code was deleted here: https://github.com/Raku/Pod-To-HTML/commit/e0e4950e5b83a9b1a35673e037d1d5beb9b80bb1#diff-d42ac4371a461e47eccdece085173230L371-L376

@uzluisf why did you delete that part?

**Comment by antoniogamiz** [comment]
Adding 
~~~
        <h1 class="title">{{title}}</h1>
        <p class="subtitle">{{subtitle}}</p>
~~~
to my mustache template solves the problem. I do not if those two lines should appear in the default template.

**Comment by uzluisf** [comment]
Hi, @antoniogamiz! Sorry for the late reply 😅😅. 

>why did you delete that part?

From the commit message:

>Instead of supplying a few semantic blocks as HTML meta tags, Pod::To::HTML now supplies all of them as regular template variables to the template.

Thus in the code neither `TITLE` nor `SUBTITLE` are treated specially ([reference](https://github.com/Raku/Pod-To-HTML/commit/e0e4950e5b83a9b1a35673e037d1d5beb9b80bb1?diff=unified#diff-d42ac4371a461e47eccdece085173230L370-R447)), instead all the [semantic blocks](https://docs.raku.org/language/pod#Semantic_blocks) declared in a Pod document are made available to a Mustache template. The [README file](https://github.com/Raku/Pod-To-HTML/blob/master/README.md) discusses this a bit more.

>I do not if those two lines should appear in the default template.

I'm not sure 🤔🤔. How else is `Template::Mustache` going to render the data unless it's specified in the template and subsequently supplied to it by `Pod::To::HTML`? Where should they appear?

**Comment by antoniogamiz** [comment]
> From the commit message:
> 
> > Instead of supplying a few semantic blocks as HTML meta tags, Pod::To::HTML now supplies all of them as regular template variables to the template.
> 

Oh, I did not understand the commit message completely, my fault, sorry. Thinking about it is better to use the semantic block as you have done, thanks for the implementation :).
