### ISSUE TITLE
Installation instruction in README does not install this distribution

### ISSUE THREAD

**Issue by skaji** [Raku/Pod-To-HTML#79]
README.md says

```
Installation
------------

From the [Raku ecosystem](https://modules.raku.org):

    $ zef install Pod::To::HTML
```

But, at the time of writing, `zef install Pod::To::HTML` installs `Pod::To::HTML:auth<github:finanalyst>`.

**Comment by skaji** [comment]
I think we can update README.md by

```
zef install 'Pod::To::HTML:auth<github:Raku>'
```

**Comment by JJ** [comment]
Thanks for the report; but not sure why that one appears by default. Please, @finanalyst, can you clarify that?
