### ISSUE TITLE
Can't install  Pod::To::HTML:ver<0.8> due to test failure

### ISSUE THREAD

**Issue by florian-pensec** [Raku/Pod-To-HTML#89]
The problem is in the title, and it happened to Documentable as well, plus other packages.

In case this is relevant here's my rakudo version, installed from the Debian repository:
perl6 -v
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.

and here's the output of zef at the test phase, for which I applied " | sort -u" for better readability:

  in block  at /home/london/.zef/store/Pod-To-HTML.git/0d94e0d4077d68b78383ecc2616a0ae50161f347/lib/Pod/To/HTML.pm6 (Pod::To::HTML) line 83
  in block <unit> at t/011-external.t line 7
  in block <unit> at t/012-multi.t line 9
  in block <unit> at t/020-code.t line 49
  in block <unit> at t/040-lists.t line 18
  in block <unit> at t/050-format-x-index.t line 9
  in block <unit> at t/060-table.t line 11
  in block <unit> at t/070-headings.t line 31
  in block <unit> at t/075-defn.t line 28
  in block <unit> at t/080-lang.t line 13
  in block <unit> at t/090-css.t line 13
  in block <unit> at t/110-issue-41.t line 15
  in block <unit> at t/111-perl6-doc-issue-2270.t line 11
  in method render at /home/london/.zef/store/Pod-To-HTML.git/0d94e0d4077d68b78383ecc2616a0ae50161f347/lib/Pod/To/HTML.pm6 (Pod::To::HTML) line 80
  in sub pod2html at /home/london/.zef/store/Pod-To-HTML.git/0d94e0d4077d68b78383ecc2616a0ae50161f347/lib/Pod/To/HTML.pm6 (Pod::To::HTML) line 412
  in sub render at /home/london/.zef/store/Pod-To-HTML.git/0d94e0d4077d68b78383ecc2616a0ae50161f347/lib/Pod/To/HTML.pm6 (Pod::To::HTML) line 424
  in sub render at /home/london/.zef/store/Pod-To-HTML.git/0d94e0d4077d68b78383ecc2616a0ae50161f347/lib/Pod/To/HTML.pm6 (Pod::To::HTML) line 426
  in sub test-files at t/011-external.t line 16
No such method 'raku' for invocant of type 'Str'. Did you mean any of these?
    rand
    take

I can get you more info if you need it.
Thanks in advance
PS : the .raku method doesn't work in my scripts or one-liners either, but the .perl method works. So maybe the problems come from my version of Rakudo (2018.12) that is way out of date ?

**Comment by JJ** [comment]
It's very likely the problem is that it does not support older versions. The `.raku` method was introduced with the renaming, probably 2019.11? It is not going to work with anything older than that, I'm afraid... Is it a problem to get a new version for you?

**Comment by florian-pensec** [comment]
No I don't have a problem in upgrading, on the contrary.
I just have to take the time and follow the instructions to install it.
At first, I was completely lost as to this history of VM and rakudo implementation, so I did the easy sudo apt install perl6 to try out.

**Comment by JJ** [comment]
Thanks, @florian-pensec, for understanding it. Good luck!
