### ISSUE TITLE
Undeclared routine: gen-closure-template

### ISSUE THREAD

**Issue by MARTIMM** [Raku/Pod-To-HTML#95]
I got the following error with the newest version
```
===SORRY!=== Error while compiling /home/Data/root-opt/Raku/rakudo/install/share/perl6/site/resources/FCC945D637300F00AEC945EAEA7B93988A79B446
===SORRY!=== Error while compiling /home/marcel/Languages/Raku/Projects/gnome-gtk3/site#sources/37400B2589913608999E43E2CEB2F69CB6E7A09C (Pod::Render)
===SORRY!=== Error while compiling /home/marcel/Languages/Raku/Projects/gnome-gtk3/site#sources/B724BB3B7903E7B04A25FE65B2CA6547625F99D8 (Pod::To::HTML)
Undeclared routine:
    gen-closure-template used at lines 240, 241, 242, 243, 244, 245, 246, 247


at /home/marcel/Languages/Raku/Projects/gnome-gtk3/site#sources/37400B2589913608999E43E2CEB2F69CB6E7A09C (Pod::Render):2

at /home/Data/root-opt/Raku/rakudo/install/share/perl6/site/resources/FCC945D637300F00AEC945EAEA7B93988A79B446:4
```
I've searched through my own software but could not find any use of it so perhaps it is defined in another module that is not installed at my machine. Come to think of it, there is no error of some missing module?

Regards,
Marcel

**Comment by finanalyst** [comment]
It seems that you have run into the Pod::To::HTML naming error. 
So, `Raku::Pod::Render` is a distribution that contains `Pod::To::HTML2`. It uses two or three templating systems, but by default uses one call RakuClosure,  which invokes `gen-closure-template`. 

`Pod::To::HTML2` **used** to be called `Pod::To::HTML` with a different auth string. But the auth was not being used by zef, so I was asked to change the name to `Pod::To::HTML2`.
This renaming took place a LONG time ago (2 years?). However, when the fez system began to be developed, somehow an older version of `Raku::Pod::Render` began to be prioritised over the new ones.

`Pod::To::HTML2` was designed to be a drop in replacement for `Pod::To::HTML`. However, it is in `Raku::Pod::Render` and that distribution has a few more dependencies. 

`Raku::Pod::Render` is used by `Collection` and allows for a considerable extension of Pod::To::HTML. You can seen some of the possibilities by looking at [some custom pod blocks](https://raku.finanalyst.org/collection-examples.html)

Work around. Remove `Raku::Pod::Render` from your installation, and also `Pod::To::HTML`. Then reinstall `Pod::To::HTML` with `auth<raku>` (I think), not `auth<fez:finanalyst>`

Hope this helps

**Comment by MARTIMM** [comment]
Took some time to get it right. In the end, I found out that the installation of all modules on my system had some problems. I noticed that zef could not deinstall modules although there weren't any errors. So, I removed the rakudo installation and zef configuration and started all over again. No problems now so everyone (me, that is) is happy now.
